### ISSUE TITLE
Compile errors with v0.8.x

### ISSUE THREAD

**Issue by igiona** [cunarist/tokio-with-wasm#25]
I have sample application that's using this crate.
The application compiles and runs under v0.7.5, but fails to compile with v0.8.2.

Compilation error:
```bash
warning: Linking globals named 'task_worker_entry_point': symbol multiply defined!

error: failed to load bitcode of module "tokio_with_wasm-9006ccaedc39aa1e.tokio_with_wasm.fc44a32a0d19019d-cgu.0.rcgu.o": 
```

Any idea what could be causing the issue?

**Comment by temeddix** [comment]
This might be because of duplicated dependencies, but without additional context it's hard to know. Version 0.8 didn't introduce changes related to that symbol problem.

Would you share your project config including `Cargo.toml` and `Cargo.lock`, if possible?

**Comment by igiona** [comment]
@temeddix apologize the delay, I haven't been able to look into this lately.

Your hint was correct!
I had another internal crate which was still referencing v0.7.x and this caused the compilation issue with v0.8.x.

Thank you 👍
